packages:
  - 'apps/*'
  - 'configs/*'
  - 'packages/*'
  - 'services/*'

catalog:
  # turbo
  '@turbo/gen': ^2.5.3
  turbo: ^2.5.3
  # turbo configs
  eslint-config-turbo: ^2.5.3
  eslint-plugin-turbo: ^2.5.3

  # configs
  eslint: ^9.27.0
  prettier: ^3.5.3

  # utils
  '@dotenvx/dotenvx': ^1.44.1
  zod: ^3.25.28

  # services
  airtable: ^0.12.2

  # css
  class-variance-authority: ^0.7.1
  # tailwindcss
  '@tailwindcss/postcss': ^4.1.7
  tailwindcss: ^4.1.7

  # react
  react: ^19.1.0
  react-dom: ^19.1.0
  # react icons
  '@icons-pack/react-simple-icons': ^12.8.0
  lucide-react: ^0.511.0
  # react forms
  '@hookform/resolvers': ^5.0.1
  react-hook-form: ^7.56.4

  # next
  next: ^15.3.2
  next-safe-action: ^7.10.8
  next-themes: ^0.4.6
  # next configs
  '@next/eslint-plugin-next': ^15.3.2

  # typescript
  typescript: ^5.8.3
  typescript-eslint: ^8.32.1
  # types
  '@types/node': ^22.15.21
  # react types
  '@types/react': ^19.1.5
  '@types/react-dom': ^19.1.5
