packages:
  - "apps/*"
  - "packages/*"

catalog:
  # next
  next: ^15.1.7
  next-themes: ^0.4.4
  # react
  react: ^19.0.0
  react-dom: ^19.0.0
  lucide-react: ^0.476.0
  # react forms
  react-hook-form: ^7.54.2
  "@hookform/resolvers": ^3.10.0
  # postcss
  postcss: ^8.5.1
  postcss-load-config: ^6.0.1
  "@tailwindcss/postcss": ^4.0.9
  # tailwindcss
  tailwindcss: ^4.0.9
  tailwindcss-intersect: ^2.1.0
  tailwind-merge: ^3.0.1
  # utils
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  zod: ^3.24.2
  # turbo
  "@turbo/gen": ^2.4.4
  # typescript
  typescript: ^5.7.3
  "@types/node": ^20
  "@types/react": ^19
  "@types/react-dom": ^19
