packages:
  - 'apps/*'
  - 'configs/*'
  - 'packages/*'
  # - 'services/*'

catalog:
  # turbo
  '@turbo/gen': ^2.5.2
  turbo: ^2.5.2
  # turbo configs
  eslint-config-turbo: ^2.5.2
  eslint-plugin-turbo: ^2.5.2

  # configs
  eslint: ^9.26.0
  prettier: ^3.5.3

  # utils
  '@dotenvx/dotenvx': ^1.43.0
  zod: ^3.24.4

  # services
  airtable: ^0.12.2

  # css
  class-variance-authority: ^0.7.1
  # tailwindcss
  '@tailwindcss/postcss': ^4.1.5
  tailwindcss: ^4.1.5

  # react
  react: ^19.1.0
  react-dom: ^19.1.0
  # react icons
  '@icons-pack/react-simple-icons': ^12.7.0
  lucide-react: ^0.507.0
  # react forms
  '@hookform/resolvers': ^5.0.1
  react-hook-form: ^7.56.2

  # next
  next: ^15.3.1
  next-safe-action: ^7.10.8
  next-themes: ^0.4.6
  # next configs
  '@next/eslint-plugin-next': ^15.3.1

  # typescript
  typescript: ^5.8.3
  typescript-eslint: ^8.31.1
  # types
  '@types/node': ^22.15.3
  # react types
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.3
