packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"
  - "services/*"

catalog:
  # api services
  airtable: ^0.12.2

  # configs and utils
  "@turbo/gen": ^2.5.0
  "@dotenvx/dotenvx": ^1.39.1
  eslint: ^9.24.0
  prettier: ^3.5.3
  zod: ^3.24.2

  # design system
  "@tailwindcss/postcss": ^4.1.3
  tailwindcss: ^4.1.3
  # css utils
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1

  # maskito masks
  "@maskito/core": ^3.6.0
  "@maskito/react": ^3.6.0

  # react
  react: ^19.1.0
  react-dom: ^19.1.0
  # react icons
  "@icons-pack/react-simple-icons": ^12.5.0
  lucide-react: ^0.487.0
  # react hook form
  "@hookform/resolvers": ^5.0.1
  react-hook-form: ^7.55.0

  # next
  next: ^15.3.0
  next-themes: ^0.4.6

  # typescript
  typescript: ^5.8.3
  # types
  "@types/node": ^22.14.0
  # react types
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1
