packages:
  - "apps/*"
  - "packages/*"

catalog:
  # next
  next: ^15.2.1
  next-themes: ^0.4.4
  # react
  react: ^19.0.0
  react-dom: ^19.0.0
  lucide-react: ^0.479.0
  # react forms
  react-hook-form: ^7.54.2
  "@hookform/resolvers": ^4.1.3
  # tailwindcss
  "@tailwindcss/postcss": ^4.0.12
  tailwindcss: ^4.0.12
  tailwindcss-intersect: ^2.1.0
  tailwind-merge: ^3.0.2
  # utils
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  zod: ^3.24.2
  # turbo
  "@turbo/gen": ^2.4.4
  # typescript
  typescript: ^5.8.2
  "@types/node": ^22.13.8
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
