packages:
  - 'apps/*'
  - 'configs/*'
  - 'packages/*'
  # - 'services/*'

catalog:
  # turbo
  '@turbo/gen': ^2.5.0
  turbo: ^2.5.0
  # turbo configs
  eslint-config-turbo: ^2.5.0
  eslint-plugin-turbo: ^2.5.0

  # configs
  eslint: ^9.24.0
  prettier: ^3.5.3

  # utils
  '@dotenvx/dotenvx': ^1.40.1
  zod: ^3.24.3

  # services
  airtable: ^0.12.2

  # css
  class-variance-authority: ^0.7.1
  # tailwindcss
  '@tailwindcss/postcss': ^4.1.4
  tailwindcss: ^4.1.4

  # forms
  '@maskito/core': ^3.7.1
  '@maskito/react': ^3.7.1

  # react
  react: ^19.1.0
  react-dom: ^19.1.0
  # react icons
  '@icons-pack/react-simple-icons': ^12.6.0
  lucide-react: ^0.488.0
  # react forms
  '@hookform/resolvers': ^5.0.1
  react-hook-form: ^7.55.0

  # next
  next: ^15.3.1
  next-safe-action: ^7.10.5
  next-themes: ^0.4.6
  # next configs
  '@next/eslint-plugin-next': ^15.3.1

  # typescript
  typescript: ^5.8.3
  typescript-eslint: ^8.30.1
  # types
  '@types/node': ^22.14.1
  # react types
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
