import { extendTailwindMerge } from 'tailwind-merge';

// Extends the default tailwind merge to include custom classes added to tailwind theme config
const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        'dark',
        'light',
        'base',
        'base-1',
        'base-2',
        'base-3',
        'base-foreground',
        'display',
        'display-1',
        'display-2',
        'display-3',
        'display-foreground',
        'panel',
        'panel-1',
        'panel-2',
        'panel-3',
        'panel-foreground',
        'edge',
        'edge-1',
        'edge-2',
        'edge-3',
        'edge-foreground',
        'shell',
        'shell-1',
        'shell-2',
        'shell-3',
        'shell-foreground',
        'cover',
        'cover-1',
        'cover-2',
        'cover-3',
        'cover-foreground',
        'background',
        'foreground',
        'input',
        'border',
        'ring',
        'card',
        'card-foreground',
        'popover',
        'popover-foreground',
        'muted',
        'muted-foreground',
        'neutral',
        'neutral-foreground',
        'primary',
        'primary-foreground',
        'secondary',
        'secondary-foreground',
        'accent',
        'accent-foreground',
        'danger',
        'danger-foreground',
      ],
      radius: ['fs-xs', 'fs-sm', 'fs-md', 'fs-lg', 'fs-xl'],
      spacing: [
        'fs-0-25',
        'fs-0-375',
        'fs-0-5',
        'fs-0-625',
        'fs-0-75',
        'fs-1',
        'fs-2',
        'fs-3',
        'fs-4',
        'fs-5',
        'fs-6',
        'fs-7',
        'fs-8',
        'fs-9',
        'fs-10',
        'fs-11',
        'fs-12',
        'fs-13',
        'fs-14',
        'fs-15',
        'fs-16',
        'fs-17',
        'fs-18',
        'fs-19',
        'fs-20',
        'fs-21',
        'fs-22',
        'fs-23',
        'fs-24',
        'fs-25',
        'fs-26',
        'fs-27',
        'fs-28',
        'fs-29',
        'fs-30',
        'fs-31',
        'fs-32',
        'fs-33',
        'fs-34',
        'fs-35',
        'fs-36',
        'fs-37',
        'fs-38',
        'fs-39',
        'fs-40',
        'fs-41',
        'fs-42',
        'fs-43',
        'fs-44',
        'fs-45',
        'fs-46',
      ],
      text: [
        'caption',
        'label',
        'body',
        'subheading',
        'subtitle',
        'heading',
        'title',
        'headline',
        'epic',
      ],
    },
    classGroups: {
      'font-size': [
        {
          text: [
            'caption',
            'label',
            'body',
            'subheading',
            'subtitle',
            'heading',
            'title',
            'headline',
            'epic',
          ],
        },
      ],
    },
  },
});

export { twMerge };
